apiVersion: batch/v1
kind: Job
metadata:
  name: counter
spec:
  template:
    spec:
      containers:
      - name: counter
        image: gcr.io/my-project-1531888882785/wordcount
        args: ["-glow", "-glow.leader", "$(MASTER)"]
        env:
          - name: MASTER
            value: "glow-master:8930"
      restartPolicy: Never
