apiVersion: v1
kind: ReplicationController
metadata:
  name: glow-node
spec:
  replicas: 3
  selector:
    glow-node: "true"
  template:
    metadata:
      labels:
        name: glow-node
        glow-node: "true"
        role: node
    spec:
      containers:
        - name: glow-node
          args: ["agent", "--dir=/data", "--master", "$(MASTER)"]
          image: gcr.io/my-project-1531888882785/glow-node
          ports:
            - containerPort: 8931
          env:
            - name: MASTER
              value: "glow-master:8930"
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          emptyDir: {}
